# Generated by Django 4.2.16 on 2026-09-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpages', to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='DocumentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ydoc_update', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ydoc_update', models.BinaryField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('mentioned_user_ids', models.JSONField(blank=True, default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='documents.document')),
                ('to_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='documents.document')),
            ],
            options={
                'unique_together': {('from_document', 'to_document')},
            },
        ),
    ]
